image: debian/sid
packages:
  - golang-go
  - debootstrap
  - libglib2.0-bin
  - systemd-container
  - zstd
sources:
  - https://git.sr.ht/~angdraug/packer-builder-nspawn
  - https://git.sr.ht/~angdraug/packer-provisioner-apt
environment:
  builder: packer-builder-nspawn
  provisioner: packer-provisioner-apt
tasks:
  # packer recommends docker.io, that mucks up network in build VM
  - setup_packer: |
      sudo apt-get --no-install-recommends --yes install packer
  - binary: |
      cd ~/${provisioner}
      go build
      ln -s ~/${provisioner}/${provisioner} ~/${builder}/
      cd ~/${builder}
      go build
  - machine: |
      cd ${builder}
      sudo systemctl start systemd-networkd.service
      sudo systemctl start systemd-resolved.service
      sudo ./test.sh
